// Package records provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package records

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for CapabilitiesAuthMode.
const (
	None CapabilitiesAuthMode = "none"
)

// Valid indicates whether the value is a known member of the CapabilitiesAuthMode enum.
func (e CapabilitiesAuthMode) Valid() bool {
	switch e {
	case None:
		return true
	default:
		return false
	}
}

// Defines values for CapabilitiesBackend.
const (
	CapabilitiesBackendFts       CapabilitiesBackend = "fts"
	CapabilitiesBackendGraph     CapabilitiesBackend = "graph"
	CapabilitiesBackendHybrid    CapabilitiesBackend = "hybrid"
	CapabilitiesBackendOpenclerk CapabilitiesBackend = "openclerk"
	CapabilitiesBackendRecords   CapabilitiesBackend = "records"
)

// Valid indicates whether the value is a known member of the CapabilitiesBackend enum.
func (e CapabilitiesBackend) Valid() bool {
	switch e {
	case CapabilitiesBackendFts:
		return true
	case CapabilitiesBackendGraph:
		return true
	case CapabilitiesBackendHybrid:
		return true
	case CapabilitiesBackendOpenclerk:
		return true
	case CapabilitiesBackendRecords:
		return true
	default:
		return false
	}
}

// Defines values for CapabilitiesExtensions.
const (
	CapabilitiesExtensionsGraph      CapabilitiesExtensions = "graph"
	CapabilitiesExtensionsProvenance CapabilitiesExtensions = "provenance"
	CapabilitiesExtensionsRecords    CapabilitiesExtensions = "records"
)

// Valid indicates whether the value is a known member of the CapabilitiesExtensions enum.
func (e CapabilitiesExtensions) Valid() bool {
	switch e {
	case CapabilitiesExtensionsGraph:
		return true
	case CapabilitiesExtensionsProvenance:
		return true
	case CapabilitiesExtensionsRecords:
		return true
	default:
		return false
	}
}

// Defines values for CapabilitiesSearchModes.
const (
	Hybrid  CapabilitiesSearchModes = "hybrid"
	Lexical CapabilitiesSearchModes = "lexical"
	Vector  CapabilitiesSearchModes = "vector"
)

// Valid indicates whether the value is a known member of the CapabilitiesSearchModes enum.
func (e CapabilitiesSearchModes) Valid() bool {
	switch e {
	case Hybrid:
		return true
	case Lexical:
		return true
	case Vector:
		return true
	default:
		return false
	}
}

// Defines values for GraphEdgeKind.
const (
	Cites    GraphEdgeKind = "cites"
	LinksTo  GraphEdgeKind = "links_to"
	Mentions GraphEdgeKind = "mentions"
)

// Valid indicates whether the value is a known member of the GraphEdgeKind enum.
func (e GraphEdgeKind) Valid() bool {
	switch e {
	case Cites:
		return true
	case LinksTo:
		return true
	case Mentions:
		return true
	default:
		return false
	}
}

// Defines values for GraphNodeType.
const (
	GraphNodeTypeChunk    GraphNodeType = "chunk"
	GraphNodeTypeDocument GraphNodeType = "document"
	GraphNodeTypeEntity   GraphNodeType = "entity"
	GraphNodeTypeHeading  GraphNodeType = "heading"
)

// Valid indicates whether the value is a known member of the GraphNodeType enum.
func (e GraphNodeType) Valid() bool {
	switch e {
	case GraphNodeTypeChunk:
		return true
	case GraphNodeTypeDocument:
		return true
	case GraphNodeTypeEntity:
		return true
	case GraphNodeTypeHeading:
		return true
	default:
		return false
	}
}

// Defines values for ProjectionStateFreshness.
const (
	Fresh ProjectionStateFreshness = "fresh"
	Stale ProjectionStateFreshness = "stale"
)

// Valid indicates whether the value is a known member of the ProjectionStateFreshness enum.
func (e ProjectionStateFreshness) Valid() bool {
	switch e {
	case Fresh:
		return true
	case Stale:
		return true
	default:
		return false
	}
}

// Defines values for ProjectionStateRefKind.
const (
	ProjectionStateRefKindChunk      ProjectionStateRefKind = "chunk"
	ProjectionStateRefKindDocument   ProjectionStateRefKind = "document"
	ProjectionStateRefKindEntity     ProjectionStateRefKind = "entity"
	ProjectionStateRefKindProjection ProjectionStateRefKind = "projection"
)

// Valid indicates whether the value is a known member of the ProjectionStateRefKind enum.
func (e ProjectionStateRefKind) Valid() bool {
	switch e {
	case ProjectionStateRefKindChunk:
		return true
	case ProjectionStateRefKindDocument:
		return true
	case ProjectionStateRefKindEntity:
		return true
	case ProjectionStateRefKindProjection:
		return true
	default:
		return false
	}
}

// Defines values for ProvenanceEventRefKind.
const (
	ProvenanceEventRefKindChunk      ProvenanceEventRefKind = "chunk"
	ProvenanceEventRefKindDocument   ProvenanceEventRefKind = "document"
	ProvenanceEventRefKindEntity     ProvenanceEventRefKind = "entity"
	ProvenanceEventRefKindProjection ProvenanceEventRefKind = "projection"
)

// Valid indicates whether the value is a known member of the ProvenanceEventRefKind enum.
func (e ProvenanceEventRefKind) Valid() bool {
	switch e {
	case ProvenanceEventRefKindChunk:
		return true
	case ProvenanceEventRefKindDocument:
		return true
	case ProvenanceEventRefKindEntity:
		return true
	case ProvenanceEventRefKindProjection:
		return true
	default:
		return false
	}
}

// AppendDocumentRequest defines model for AppendDocumentRequest.
type AppendDocumentRequest struct {
	Content string `json:"content"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	AuthMode    CapabilitiesAuthMode      `json:"authMode"`
	Backend     CapabilitiesBackend       `json:"backend"`
	Extensions  []CapabilitiesExtensions  `json:"extensions"`
	SearchModes []CapabilitiesSearchModes `json:"searchModes"`
}

// CapabilitiesAuthMode defines model for Capabilities.AuthMode.
type CapabilitiesAuthMode string

// CapabilitiesBackend defines model for Capabilities.Backend.
type CapabilitiesBackend string

// CapabilitiesExtensions defines model for Capabilities.Extensions.
type CapabilitiesExtensions string

// CapabilitiesSearchModes defines model for Capabilities.SearchModes.
type CapabilitiesSearchModes string

// Chunk defines model for Chunk.
type Chunk struct {
	ChunkId   string `json:"chunkId"`
	Content   string `json:"content"`
	DocId     string `json:"docId"`
	Heading   string `json:"heading"`
	LineEnd   int    `json:"lineEnd"`
	LineStart int    `json:"lineStart"`
	Path      string `json:"path"`
}

// Citation defines model for Citation.
type Citation struct {
	ChunkId   string  `json:"chunkId"`
	DocId     string  `json:"docId"`
	Heading   *string `json:"heading,omitempty"`
	LineEnd   int     `json:"lineEnd"`
	LineStart int     `json:"lineStart"`
	Path      string  `json:"path"`
}

// CreateDocumentRequest defines model for CreateDocumentRequest.
type CreateDocumentRequest struct {
	Body  string `json:"body"`
	Path  string `json:"path"`
	Title string `json:"title"`
}

// Document defines model for Document.
type Document struct {
	Body      string            `json:"body"`
	CreatedAt time.Time         `json:"createdAt"`
	DocId     string            `json:"docId"`
	Headings  []string          `json:"headings"`
	Metadata  map[string]string `json:"metadata"`
	Path      string            `json:"path"`
	Title     string            `json:"title"`
	UpdatedAt time.Time         `json:"updatedAt"`
}

// DocumentLink defines model for DocumentLink.
type DocumentLink struct {
	Citations []Citation `json:"citations"`
	DocId     string     `json:"docId"`
	Path      string     `json:"path"`
	Title     string     `json:"title"`
}

// DocumentLinksResponse defines model for DocumentLinksResponse.
type DocumentLinksResponse struct {
	DocId    string         `json:"docId"`
	Incoming []DocumentLink `json:"incoming"`
	Outgoing []DocumentLink `json:"outgoing"`
}

// DocumentListResponse defines model for DocumentListResponse.
type DocumentListResponse struct {
	Documents []DocumentSummary `json:"documents"`
	PageInfo  PageInfo          `json:"pageInfo"`
}

// DocumentSummary defines model for DocumentSummary.
type DocumentSummary struct {
	DocId     string            `json:"docId"`
	Metadata  map[string]string `json:"metadata"`
	Path      string            `json:"path"`
	Title     string            `json:"title"`
	UpdatedAt time.Time         `json:"updatedAt"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Code      string                  `json:"code"`
	Details   *map[string]interface{} `json:"details,omitempty"`
	Message   string                  `json:"message"`
	RequestId string                  `json:"requestId"`
	Retryable bool                    `json:"retryable"`
}

// GraphEdge defines model for GraphEdge.
type GraphEdge struct {
	Citations  []Citation    `json:"citations"`
	EdgeId     string        `json:"edgeId"`
	FromNodeId string        `json:"fromNodeId"`
	Kind       GraphEdgeKind `json:"kind"`
	ToNodeId   string        `json:"toNodeId"`
}

// GraphEdgeKind defines model for GraphEdge.Kind.
type GraphEdgeKind string

// GraphNeighborhoodRequest defines model for GraphNeighborhoodRequest.
type GraphNeighborhoodRequest struct {
	ChunkId *string `json:"chunkId,omitempty"`
	DocId   *string `json:"docId,omitempty"`
	Limit   *int    `json:"limit,omitempty"`
	NodeId  *string `json:"nodeId,omitempty"`
}

// GraphNeighborhoodResponse defines model for GraphNeighborhoodResponse.
type GraphNeighborhoodResponse struct {
	Edges []GraphEdge `json:"edges"`
	Nodes []GraphNode `json:"nodes"`
}

// GraphNode defines model for GraphNode.
type GraphNode struct {
	Citations []Citation    `json:"citations"`
	Label     string        `json:"label"`
	NodeId    string        `json:"nodeId"`
	Type      GraphNodeType `json:"type"`
}

// GraphNodeType defines model for GraphNode.Type.
type GraphNodeType string

// PageInfo defines model for PageInfo.
type PageInfo struct {
	HasMore    bool    `json:"hasMore"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

// ProjectionState defines model for ProjectionState.
type ProjectionState struct {
	Details           map[string]string        `json:"details"`
	Freshness         ProjectionStateFreshness `json:"freshness"`
	Projection        string                   `json:"projection"`
	ProjectionVersion string                   `json:"projectionVersion"`
	RefId             string                   `json:"refId"`
	RefKind           ProjectionStateRefKind   `json:"refKind"`
	SourceRef         string                   `json:"sourceRef"`
	UpdatedAt         time.Time                `json:"updatedAt"`
}

// ProjectionStateFreshness defines model for ProjectionState.Freshness.
type ProjectionStateFreshness string

// ProjectionStateRefKind defines model for ProjectionState.RefKind.
type ProjectionStateRefKind string

// ProjectionStatesResponse defines model for ProjectionStatesResponse.
type ProjectionStatesResponse struct {
	PageInfo    PageInfo          `json:"pageInfo"`
	Projections []ProjectionState `json:"projections"`
}

// ProvenanceEvent defines model for ProvenanceEvent.
type ProvenanceEvent struct {
	Details    map[string]string      `json:"details"`
	EventId    string                 `json:"eventId"`
	EventType  string                 `json:"eventType"`
	OccurredAt time.Time              `json:"occurredAt"`
	RefId      string                 `json:"refId"`
	RefKind    ProvenanceEventRefKind `json:"refKind"`
	SourceRef  string                 `json:"sourceRef"`
}

// ProvenanceEventRefKind defines model for ProvenanceEvent.RefKind.
type ProvenanceEventRefKind string

// ProvenanceEventsResponse defines model for ProvenanceEventsResponse.
type ProvenanceEventsResponse struct {
	Events   []ProvenanceEvent `json:"events"`
	PageInfo PageInfo          `json:"pageInfo"`
}

// RecordEntity defines model for RecordEntity.
type RecordEntity struct {
	Citations  []Citation   `json:"citations"`
	EntityId   string       `json:"entityId"`
	EntityType string       `json:"entityType"`
	Facts      []RecordFact `json:"facts"`
	Name       string       `json:"name"`
	Summary    string       `json:"summary"`
	UpdatedAt  time.Time    `json:"updatedAt"`
}

// RecordFact defines model for RecordFact.
type RecordFact struct {
	Key        string     `json:"key"`
	ObservedAt *time.Time `json:"observedAt,omitempty"`
	Value      string     `json:"value"`
}

// RecordsLookupRequest defines model for RecordsLookupRequest.
type RecordsLookupRequest struct {
	Cursor     *string `json:"cursor,omitempty"`
	EntityType *string `json:"entityType,omitempty"`
	Limit      *int    `json:"limit,omitempty"`
	Text       string  `json:"text"`
}

// RecordsLookupResponse defines model for RecordsLookupResponse.
type RecordsLookupResponse struct {
	Entities []RecordEntity `json:"entities"`
	PageInfo PageInfo       `json:"pageInfo"`
}

// ReplaceSectionRequest defines model for ReplaceSectionRequest.
type ReplaceSectionRequest struct {
	Content string `json:"content"`
	Heading string `json:"heading"`
}

// SearchHit defines model for SearchHit.
type SearchHit struct {
	ChunkId   string     `json:"chunkId"`
	Citations []Citation `json:"citations"`
	DocId     string     `json:"docId"`
	Rank      int        `json:"rank"`
	Score     float64    `json:"score"`
	Snippet   string     `json:"snippet"`
	Title     string     `json:"title"`
}

// SearchQuery defines model for SearchQuery.
type SearchQuery struct {
	Cursor        *string `json:"cursor,omitempty"`
	Limit         *int    `json:"limit,omitempty"`
	MetadataKey   *string `json:"metadataKey,omitempty"`
	MetadataValue *string `json:"metadataValue,omitempty"`
	PathPrefix    *string `json:"pathPrefix,omitempty"`
	Text          string  `json:"text"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Hits     []SearchHit `json:"hits"`
	PageInfo PageInfo    `json:"pageInfo"`
}

// ChunkId defines model for ChunkId.
type ChunkId = string

// DocId defines model for DocId.
type DocId = string

// EntityId defines model for EntityId.
type EntityId = string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = ErrorEnvelope

// ListDocumentsParams defines parameters for ListDocuments.
type ListDocumentsParams struct {
	PathPrefix    *string `form:"pathPrefix,omitempty" json:"pathPrefix,omitempty"`
	MetadataKey   *string `form:"metadataKey,omitempty" json:"metadataKey,omitempty"`
	MetadataValue *string `form:"metadataValue,omitempty" json:"metadataValue,omitempty"`
	Limit         *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor        *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListProvenanceEventsParams defines parameters for ListProvenanceEvents.
type ListProvenanceEventsParams struct {
	RefKind   *string `form:"refKind,omitempty" json:"refKind,omitempty"`
	RefId     *string `form:"refId,omitempty" json:"refId,omitempty"`
	SourceRef *string `form:"sourceRef,omitempty" json:"sourceRef,omitempty"`
	Limit     *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor    *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListProjectionStatesParams defines parameters for ListProjectionStates.
type ListProjectionStatesParams struct {
	Projection *string `form:"projection,omitempty" json:"projection,omitempty"`
	RefKind    *string `form:"refKind,omitempty" json:"refKind,omitempty"`
	RefId      *string `form:"refId,omitempty" json:"refId,omitempty"`
	Limit      *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor     *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateDocumentJSONRequestBody defines body for CreateDocument for application/json ContentType.
type CreateDocumentJSONRequestBody = CreateDocumentRequest

// AppendDocumentJSONRequestBody defines body for AppendDocument for application/json ContentType.
type AppendDocumentJSONRequestBody = AppendDocumentRequest

// ReplaceDocumentSectionJSONRequestBody defines body for ReplaceDocumentSection for application/json ContentType.
type ReplaceDocumentSectionJSONRequestBody = ReplaceSectionRequest

// RecordsLookupJSONRequestBody defines body for RecordsLookup for application/json ContentType.
type RecordsLookupJSONRequestBody = RecordsLookupRequest

// SearchQueryJSONRequestBody defines body for SearchQuery for application/json ContentType.
type SearchQueryJSONRequestBody = SearchQuery

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetCapabilities request
	GetCapabilities(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetChunk request
	GetChunk(ctx context.Context, chunkId ChunkId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListDocuments request
	ListDocuments(ctx context.Context, params *ListDocumentsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateDocumentWithBody request with any body
	CreateDocumentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateDocument(ctx context.Context, body CreateDocumentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDocument request
	GetDocument(ctx context.Context, docId DocId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDocumentLinks request
	GetDocumentLinks(ctx context.Context, docId DocId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AppendDocumentWithBody request with any body
	AppendDocumentWithBody(ctx context.Context, docId DocId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AppendDocument(ctx context.Context, docId DocId, body AppendDocumentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReplaceDocumentSectionWithBody request with any body
	ReplaceDocumentSectionWithBody(ctx context.Context, docId DocId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ReplaceDocumentSection(ctx context.Context, docId DocId, body ReplaceDocumentSectionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRecordEntity request
	GetRecordEntity(ctx context.Context, entityId EntityId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RecordsLookupWithBody request with any body
	RecordsLookupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RecordsLookup(ctx context.Context, body RecordsLookupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListProvenanceEvents request
	ListProvenanceEvents(ctx context.Context, params *ListProvenanceEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListProjectionStates request
	ListProjectionStates(ctx context.Context, params *ListProjectionStatesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchQueryWithBody request with any body
	SearchQueryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SearchQuery(ctx context.Context, body SearchQueryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetCapabilities(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCapabilitiesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetChunk(ctx context.Context, chunkId ChunkId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetChunkRequest(c.Server, chunkId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListDocuments(ctx context.Context, params *ListDocumentsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDocumentsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDocumentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDocumentRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDocument(ctx context.Context, body CreateDocumentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDocumentRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDocument(ctx context.Context, docId DocId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDocumentRequest(c.Server, docId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDocumentLinks(ctx context.Context, docId DocId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDocumentLinksRequest(c.Server, docId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AppendDocumentWithBody(ctx context.Context, docId DocId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAppendDocumentRequestWithBody(c.Server, docId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AppendDocument(ctx context.Context, docId DocId, body AppendDocumentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAppendDocumentRequest(c.Server, docId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReplaceDocumentSectionWithBody(ctx context.Context, docId DocId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceDocumentSectionRequestWithBody(c.Server, docId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReplaceDocumentSection(ctx context.Context, docId DocId, body ReplaceDocumentSectionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceDocumentSectionRequest(c.Server, docId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRecordEntity(ctx context.Context, entityId EntityId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRecordEntityRequest(c.Server, entityId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RecordsLookupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRecordsLookupRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RecordsLookup(ctx context.Context, body RecordsLookupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRecordsLookupRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListProvenanceEvents(ctx context.Context, params *ListProvenanceEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListProvenanceEventsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListProjectionStates(ctx context.Context, params *ListProjectionStatesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListProjectionStatesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchQueryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchQueryRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchQuery(ctx context.Context, body SearchQueryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchQueryRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCapabilitiesRequest generates requests for GetCapabilities
func NewGetCapabilitiesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/capabilities")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetChunkRequest generates requests for GetChunk
func NewGetChunkRequest(server string, chunkId ChunkId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "chunkId", chunkId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/chunks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListDocumentsRequest generates requests for ListDocuments
func NewListDocumentsRequest(server string, params *ListDocumentsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/documents")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.PathPrefix != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pathPrefix", *params.PathPrefix, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MetadataKey != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "metadataKey", *params.MetadataKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MetadataValue != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "metadataValue", *params.MetadataValue, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateDocumentRequest calls the generic CreateDocument builder with application/json body
func NewCreateDocumentRequest(server string, body CreateDocumentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateDocumentRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateDocumentRequestWithBody generates requests for CreateDocument with any type of body
func NewCreateDocumentRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/documents")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetDocumentRequest generates requests for GetDocument
func NewGetDocumentRequest(server string, docId DocId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "docId", docId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/documents/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDocumentLinksRequest generates requests for GetDocumentLinks
func NewGetDocumentLinksRequest(server string, docId DocId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "docId", docId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/documents/%s/links", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAppendDocumentRequest calls the generic AppendDocument builder with application/json body
func NewAppendDocumentRequest(server string, docId DocId, body AppendDocumentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAppendDocumentRequestWithBody(server, docId, "application/json", bodyReader)
}

// NewAppendDocumentRequestWithBody generates requests for AppendDocument with any type of body
func NewAppendDocumentRequestWithBody(server string, docId DocId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "docId", docId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/documents/%s:append", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReplaceDocumentSectionRequest calls the generic ReplaceDocumentSection builder with application/json body
func NewReplaceDocumentSectionRequest(server string, docId DocId, body ReplaceDocumentSectionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReplaceDocumentSectionRequestWithBody(server, docId, "application/json", bodyReader)
}

// NewReplaceDocumentSectionRequestWithBody generates requests for ReplaceDocumentSection with any type of body
func NewReplaceDocumentSectionRequestWithBody(server string, docId DocId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "docId", docId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/documents/%s:replace-section", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetRecordEntityRequest generates requests for GetRecordEntity
func NewGetRecordEntityRequest(server string, entityId EntityId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "entityId", entityId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/extensions/records/entities/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRecordsLookupRequest calls the generic RecordsLookup builder with application/json body
func NewRecordsLookupRequest(server string, body RecordsLookupJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRecordsLookupRequestWithBody(server, "application/json", bodyReader)
}

// NewRecordsLookupRequestWithBody generates requests for RecordsLookup with any type of body
func NewRecordsLookupRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/extensions/records/lookup")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListProvenanceEventsRequest generates requests for ListProvenanceEvents
func NewListProvenanceEventsRequest(server string, params *ListProvenanceEventsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/provenance/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.RefKind != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "refKind", *params.RefKind, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RefId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "refId", *params.RefId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SourceRef != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sourceRef", *params.SourceRef, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListProjectionStatesRequest generates requests for ListProjectionStates
func NewListProjectionStatesRequest(server string, params *ListProjectionStatesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/provenance/projections")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Projection != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "projection", *params.Projection, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RefKind != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "refKind", *params.RefKind, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RefId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "refId", *params.RefId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSearchQueryRequest calls the generic SearchQuery builder with application/json body
func NewSearchQueryRequest(server string, body SearchQueryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSearchQueryRequestWithBody(server, "application/json", bodyReader)
}

// NewSearchQueryRequestWithBody generates requests for SearchQuery with any type of body
func NewSearchQueryRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/search/query")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetCapabilitiesWithResponse request
	GetCapabilitiesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCapabilitiesResp, error)

	// GetChunkWithResponse request
	GetChunkWithResponse(ctx context.Context, chunkId ChunkId, reqEditors ...RequestEditorFn) (*GetChunkResp, error)

	// ListDocumentsWithResponse request
	ListDocumentsWithResponse(ctx context.Context, params *ListDocumentsParams, reqEditors ...RequestEditorFn) (*ListDocumentsResp, error)

	// CreateDocumentWithBodyWithResponse request with any body
	CreateDocumentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDocumentResp, error)

	CreateDocumentWithResponse(ctx context.Context, body CreateDocumentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDocumentResp, error)

	// GetDocumentWithResponse request
	GetDocumentWithResponse(ctx context.Context, docId DocId, reqEditors ...RequestEditorFn) (*GetDocumentResp, error)

	// GetDocumentLinksWithResponse request
	GetDocumentLinksWithResponse(ctx context.Context, docId DocId, reqEditors ...RequestEditorFn) (*GetDocumentLinksResp, error)

	// AppendDocumentWithBodyWithResponse request with any body
	AppendDocumentWithBodyWithResponse(ctx context.Context, docId DocId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AppendDocumentResp, error)

	AppendDocumentWithResponse(ctx context.Context, docId DocId, body AppendDocumentJSONRequestBody, reqEditors ...RequestEditorFn) (*AppendDocumentResp, error)

	// ReplaceDocumentSectionWithBodyWithResponse request with any body
	ReplaceDocumentSectionWithBodyWithResponse(ctx context.Context, docId DocId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReplaceDocumentSectionResp, error)

	ReplaceDocumentSectionWithResponse(ctx context.Context, docId DocId, body ReplaceDocumentSectionJSONRequestBody, reqEditors ...RequestEditorFn) (*ReplaceDocumentSectionResp, error)

	// GetRecordEntityWithResponse request
	GetRecordEntityWithResponse(ctx context.Context, entityId EntityId, reqEditors ...RequestEditorFn) (*GetRecordEntityResp, error)

	// RecordsLookupWithBodyWithResponse request with any body
	RecordsLookupWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RecordsLookupResp, error)

	RecordsLookupWithResponse(ctx context.Context, body RecordsLookupJSONRequestBody, reqEditors ...RequestEditorFn) (*RecordsLookupResp, error)

	// ListProvenanceEventsWithResponse request
	ListProvenanceEventsWithResponse(ctx context.Context, params *ListProvenanceEventsParams, reqEditors ...RequestEditorFn) (*ListProvenanceEventsResp, error)

	// ListProjectionStatesWithResponse request
	ListProjectionStatesWithResponse(ctx context.Context, params *ListProjectionStatesParams, reqEditors ...RequestEditorFn) (*ListProjectionStatesResp, error)

	// SearchQueryWithBodyWithResponse request with any body
	SearchQueryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SearchQueryResp, error)

	SearchQueryWithResponse(ctx context.Context, body SearchQueryJSONRequestBody, reqEditors ...RequestEditorFn) (*SearchQueryResp, error)
}

type GetCapabilitiesResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Capabilities
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetCapabilitiesResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCapabilitiesResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetChunkResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Chunk
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetChunkResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetChunkResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListDocumentsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DocumentListResponse
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListDocumentsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDocumentsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateDocumentResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Document
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateDocumentResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateDocumentResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDocumentResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Document
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetDocumentResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDocumentResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDocumentLinksResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DocumentLinksResponse
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetDocumentLinksResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDocumentLinksResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AppendDocumentResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Document
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r AppendDocumentResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AppendDocumentResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ReplaceDocumentSectionResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Document
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ReplaceDocumentSectionResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReplaceDocumentSectionResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRecordEntityResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RecordEntity
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetRecordEntityResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRecordEntityResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RecordsLookupResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RecordsLookupResponse
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r RecordsLookupResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RecordsLookupResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListProvenanceEventsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ProvenanceEventsResponse
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListProvenanceEventsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListProvenanceEventsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListProjectionStatesResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ProjectionStatesResponse
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListProjectionStatesResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListProjectionStatesResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SearchQueryResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SearchResponse
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r SearchQueryResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchQueryResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetCapabilitiesWithResponse request returning *GetCapabilitiesResp
func (c *ClientWithResponses) GetCapabilitiesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCapabilitiesResp, error) {
	rsp, err := c.GetCapabilities(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCapabilitiesResp(rsp)
}

// GetChunkWithResponse request returning *GetChunkResp
func (c *ClientWithResponses) GetChunkWithResponse(ctx context.Context, chunkId ChunkId, reqEditors ...RequestEditorFn) (*GetChunkResp, error) {
	rsp, err := c.GetChunk(ctx, chunkId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetChunkResp(rsp)
}

// ListDocumentsWithResponse request returning *ListDocumentsResp
func (c *ClientWithResponses) ListDocumentsWithResponse(ctx context.Context, params *ListDocumentsParams, reqEditors ...RequestEditorFn) (*ListDocumentsResp, error) {
	rsp, err := c.ListDocuments(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDocumentsResp(rsp)
}

// CreateDocumentWithBodyWithResponse request with arbitrary body returning *CreateDocumentResp
func (c *ClientWithResponses) CreateDocumentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDocumentResp, error) {
	rsp, err := c.CreateDocumentWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDocumentResp(rsp)
}

func (c *ClientWithResponses) CreateDocumentWithResponse(ctx context.Context, body CreateDocumentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDocumentResp, error) {
	rsp, err := c.CreateDocument(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDocumentResp(rsp)
}

// GetDocumentWithResponse request returning *GetDocumentResp
func (c *ClientWithResponses) GetDocumentWithResponse(ctx context.Context, docId DocId, reqEditors ...RequestEditorFn) (*GetDocumentResp, error) {
	rsp, err := c.GetDocument(ctx, docId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDocumentResp(rsp)
}

// GetDocumentLinksWithResponse request returning *GetDocumentLinksResp
func (c *ClientWithResponses) GetDocumentLinksWithResponse(ctx context.Context, docId DocId, reqEditors ...RequestEditorFn) (*GetDocumentLinksResp, error) {
	rsp, err := c.GetDocumentLinks(ctx, docId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDocumentLinksResp(rsp)
}

// AppendDocumentWithBodyWithResponse request with arbitrary body returning *AppendDocumentResp
func (c *ClientWithResponses) AppendDocumentWithBodyWithResponse(ctx context.Context, docId DocId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AppendDocumentResp, error) {
	rsp, err := c.AppendDocumentWithBody(ctx, docId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAppendDocumentResp(rsp)
}

func (c *ClientWithResponses) AppendDocumentWithResponse(ctx context.Context, docId DocId, body AppendDocumentJSONRequestBody, reqEditors ...RequestEditorFn) (*AppendDocumentResp, error) {
	rsp, err := c.AppendDocument(ctx, docId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAppendDocumentResp(rsp)
}

// ReplaceDocumentSectionWithBodyWithResponse request with arbitrary body returning *ReplaceDocumentSectionResp
func (c *ClientWithResponses) ReplaceDocumentSectionWithBodyWithResponse(ctx context.Context, docId DocId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReplaceDocumentSectionResp, error) {
	rsp, err := c.ReplaceDocumentSectionWithBody(ctx, docId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplaceDocumentSectionResp(rsp)
}

func (c *ClientWithResponses) ReplaceDocumentSectionWithResponse(ctx context.Context, docId DocId, body ReplaceDocumentSectionJSONRequestBody, reqEditors ...RequestEditorFn) (*ReplaceDocumentSectionResp, error) {
	rsp, err := c.ReplaceDocumentSection(ctx, docId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplaceDocumentSectionResp(rsp)
}

// GetRecordEntityWithResponse request returning *GetRecordEntityResp
func (c *ClientWithResponses) GetRecordEntityWithResponse(ctx context.Context, entityId EntityId, reqEditors ...RequestEditorFn) (*GetRecordEntityResp, error) {
	rsp, err := c.GetRecordEntity(ctx, entityId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRecordEntityResp(rsp)
}

// RecordsLookupWithBodyWithResponse request with arbitrary body returning *RecordsLookupResp
func (c *ClientWithResponses) RecordsLookupWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RecordsLookupResp, error) {
	rsp, err := c.RecordsLookupWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRecordsLookupResp(rsp)
}

func (c *ClientWithResponses) RecordsLookupWithResponse(ctx context.Context, body RecordsLookupJSONRequestBody, reqEditors ...RequestEditorFn) (*RecordsLookupResp, error) {
	rsp, err := c.RecordsLookup(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRecordsLookupResp(rsp)
}

// ListProvenanceEventsWithResponse request returning *ListProvenanceEventsResp
func (c *ClientWithResponses) ListProvenanceEventsWithResponse(ctx context.Context, params *ListProvenanceEventsParams, reqEditors ...RequestEditorFn) (*ListProvenanceEventsResp, error) {
	rsp, err := c.ListProvenanceEvents(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListProvenanceEventsResp(rsp)
}

// ListProjectionStatesWithResponse request returning *ListProjectionStatesResp
func (c *ClientWithResponses) ListProjectionStatesWithResponse(ctx context.Context, params *ListProjectionStatesParams, reqEditors ...RequestEditorFn) (*ListProjectionStatesResp, error) {
	rsp, err := c.ListProjectionStates(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListProjectionStatesResp(rsp)
}

// SearchQueryWithBodyWithResponse request with arbitrary body returning *SearchQueryResp
func (c *ClientWithResponses) SearchQueryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SearchQueryResp, error) {
	rsp, err := c.SearchQueryWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchQueryResp(rsp)
}

func (c *ClientWithResponses) SearchQueryWithResponse(ctx context.Context, body SearchQueryJSONRequestBody, reqEditors ...RequestEditorFn) (*SearchQueryResp, error) {
	rsp, err := c.SearchQuery(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchQueryResp(rsp)
}

// ParseGetCapabilitiesResp parses an HTTP response from a GetCapabilitiesWithResponse call
func ParseGetCapabilitiesResp(rsp *http.Response) (*GetCapabilitiesResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCapabilitiesResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Capabilities
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetChunkResp parses an HTTP response from a GetChunkWithResponse call
func ParseGetChunkResp(rsp *http.Response) (*GetChunkResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetChunkResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Chunk
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseListDocumentsResp parses an HTTP response from a ListDocumentsWithResponse call
func ParseListDocumentsResp(rsp *http.Response) (*ListDocumentsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDocumentsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DocumentListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateDocumentResp parses an HTTP response from a CreateDocumentWithResponse call
func ParseCreateDocumentResp(rsp *http.Response) (*CreateDocumentResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateDocumentResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Document
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetDocumentResp parses an HTTP response from a GetDocumentWithResponse call
func ParseGetDocumentResp(rsp *http.Response) (*GetDocumentResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDocumentResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Document
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetDocumentLinksResp parses an HTTP response from a GetDocumentLinksWithResponse call
func ParseGetDocumentLinksResp(rsp *http.Response) (*GetDocumentLinksResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDocumentLinksResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DocumentLinksResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseAppendDocumentResp parses an HTTP response from a AppendDocumentWithResponse call
func ParseAppendDocumentResp(rsp *http.Response) (*AppendDocumentResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AppendDocumentResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Document
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseReplaceDocumentSectionResp parses an HTTP response from a ReplaceDocumentSectionWithResponse call
func ParseReplaceDocumentSectionResp(rsp *http.Response) (*ReplaceDocumentSectionResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReplaceDocumentSectionResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Document
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetRecordEntityResp parses an HTTP response from a GetRecordEntityWithResponse call
func ParseGetRecordEntityResp(rsp *http.Response) (*GetRecordEntityResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRecordEntityResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RecordEntity
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseRecordsLookupResp parses an HTTP response from a RecordsLookupWithResponse call
func ParseRecordsLookupResp(rsp *http.Response) (*RecordsLookupResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RecordsLookupResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RecordsLookupResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseListProvenanceEventsResp parses an HTTP response from a ListProvenanceEventsWithResponse call
func ParseListProvenanceEventsResp(rsp *http.Response) (*ListProvenanceEventsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListProvenanceEventsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProvenanceEventsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseListProjectionStatesResp parses an HTTP response from a ListProjectionStatesWithResponse call
func ParseListProjectionStatesResp(rsp *http.Response) (*ListProjectionStatesResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListProjectionStatesResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProjectionStatesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseSearchQueryResp parses an HTTP response from a SearchQueryWithResponse call
func ParseSearchQueryResp(rsp *http.Response) (*SearchQueryResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchQueryResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SearchResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
