//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for CapabilitiesAuthMode.
const (
	None CapabilitiesAuthMode = "none"
)

// Valid indicates whether the value is a known member of the CapabilitiesAuthMode enum.
func (e CapabilitiesAuthMode) Valid() bool {
	switch e {
	case None:
		return true
	default:
		return false
	}
}

// Defines values for CapabilitiesBackend.
const (
	CapabilitiesBackendFts     CapabilitiesBackend = "fts"
	CapabilitiesBackendGraph   CapabilitiesBackend = "graph"
	CapabilitiesBackendHybrid  CapabilitiesBackend = "hybrid"
	CapabilitiesBackendRecords CapabilitiesBackend = "records"
)

// Valid indicates whether the value is a known member of the CapabilitiesBackend enum.
func (e CapabilitiesBackend) Valid() bool {
	switch e {
	case CapabilitiesBackendFts:
		return true
	case CapabilitiesBackendGraph:
		return true
	case CapabilitiesBackendHybrid:
		return true
	case CapabilitiesBackendRecords:
		return true
	default:
		return false
	}
}

// Defines values for CapabilitiesExtensions.
const (
	CapabilitiesExtensionsGraph   CapabilitiesExtensions = "graph"
	CapabilitiesExtensionsRecords CapabilitiesExtensions = "records"
)

// Valid indicates whether the value is a known member of the CapabilitiesExtensions enum.
func (e CapabilitiesExtensions) Valid() bool {
	switch e {
	case CapabilitiesExtensionsGraph:
		return true
	case CapabilitiesExtensionsRecords:
		return true
	default:
		return false
	}
}

// Defines values for CapabilitiesSearchModes.
const (
	Hybrid  CapabilitiesSearchModes = "hybrid"
	Lexical CapabilitiesSearchModes = "lexical"
	Vector  CapabilitiesSearchModes = "vector"
)

// Valid indicates whether the value is a known member of the CapabilitiesSearchModes enum.
func (e CapabilitiesSearchModes) Valid() bool {
	switch e {
	case Hybrid:
		return true
	case Lexical:
		return true
	case Vector:
		return true
	default:
		return false
	}
}

// Defines values for GraphEdgeKind.
const (
	Cites    GraphEdgeKind = "cites"
	LinksTo  GraphEdgeKind = "links_to"
	Mentions GraphEdgeKind = "mentions"
)

// Valid indicates whether the value is a known member of the GraphEdgeKind enum.
func (e GraphEdgeKind) Valid() bool {
	switch e {
	case Cites:
		return true
	case LinksTo:
		return true
	case Mentions:
		return true
	default:
		return false
	}
}

// Defines values for GraphNodeType.
const (
	GraphNodeTypeChunk    GraphNodeType = "chunk"
	GraphNodeTypeDocument GraphNodeType = "document"
	GraphNodeTypeEntity   GraphNodeType = "entity"
	GraphNodeTypeHeading  GraphNodeType = "heading"
)

// Valid indicates whether the value is a known member of the GraphNodeType enum.
func (e GraphNodeType) Valid() bool {
	switch e {
	case GraphNodeTypeChunk:
		return true
	case GraphNodeTypeDocument:
		return true
	case GraphNodeTypeEntity:
		return true
	case GraphNodeTypeHeading:
		return true
	default:
		return false
	}
}

// AppendDocumentRequest defines model for AppendDocumentRequest.
type AppendDocumentRequest struct {
	Content string `json:"content"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	AuthMode    CapabilitiesAuthMode      `json:"authMode"`
	Backend     CapabilitiesBackend       `json:"backend"`
	Extensions  []CapabilitiesExtensions  `json:"extensions"`
	SearchModes []CapabilitiesSearchModes `json:"searchModes"`
}

// CapabilitiesAuthMode defines model for Capabilities.AuthMode.
type CapabilitiesAuthMode string

// CapabilitiesBackend defines model for Capabilities.Backend.
type CapabilitiesBackend string

// CapabilitiesExtensions defines model for Capabilities.Extensions.
type CapabilitiesExtensions string

// CapabilitiesSearchModes defines model for Capabilities.SearchModes.
type CapabilitiesSearchModes string

// Chunk defines model for Chunk.
type Chunk struct {
	ChunkId   string `json:"chunkId"`
	Content   string `json:"content"`
	DocId     string `json:"docId"`
	Heading   string `json:"heading"`
	LineEnd   int    `json:"lineEnd"`
	LineStart int    `json:"lineStart"`
	Path      string `json:"path"`
}

// Citation defines model for Citation.
type Citation struct {
	ChunkId   string  `json:"chunkId"`
	DocId     string  `json:"docId"`
	Heading   *string `json:"heading,omitempty"`
	LineEnd   int     `json:"lineEnd"`
	LineStart int     `json:"lineStart"`
	Path      string  `json:"path"`
}

// CreateDocumentRequest defines model for CreateDocumentRequest.
type CreateDocumentRequest struct {
	Body  string `json:"body"`
	Path  string `json:"path"`
	Title string `json:"title"`
}

// Document defines model for Document.
type Document struct {
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"createdAt"`
	DocId     string    `json:"docId"`
	Headings  []string  `json:"headings"`
	Path      string    `json:"path"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Code      string                  `json:"code"`
	Details   *map[string]interface{} `json:"details,omitempty"`
	Message   string                  `json:"message"`
	RequestId string                  `json:"requestId"`
	Retryable bool                    `json:"retryable"`
}

// GraphEdge defines model for GraphEdge.
type GraphEdge struct {
	Citations  []Citation    `json:"citations"`
	EdgeId     string        `json:"edgeId"`
	FromNodeId string        `json:"fromNodeId"`
	Kind       GraphEdgeKind `json:"kind"`
	ToNodeId   string        `json:"toNodeId"`
}

// GraphEdgeKind defines model for GraphEdge.Kind.
type GraphEdgeKind string

// GraphNeighborhoodRequest defines model for GraphNeighborhoodRequest.
type GraphNeighborhoodRequest struct {
	ChunkId *string `json:"chunkId,omitempty"`
	DocId   *string `json:"docId,omitempty"`
	Limit   *int    `json:"limit,omitempty"`
	NodeId  *string `json:"nodeId,omitempty"`
}

// GraphNeighborhoodResponse defines model for GraphNeighborhoodResponse.
type GraphNeighborhoodResponse struct {
	Edges []GraphEdge `json:"edges"`
	Nodes []GraphNode `json:"nodes"`
}

// GraphNode defines model for GraphNode.
type GraphNode struct {
	Citations []Citation    `json:"citations"`
	Label     string        `json:"label"`
	NodeId    string        `json:"nodeId"`
	Type      GraphNodeType `json:"type"`
}

// GraphNodeType defines model for GraphNode.Type.
type GraphNodeType string

// PageInfo defines model for PageInfo.
type PageInfo struct {
	HasMore    bool    `json:"hasMore"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

// RecordEntity defines model for RecordEntity.
type RecordEntity struct {
	Citations  []Citation   `json:"citations"`
	EntityId   string       `json:"entityId"`
	EntityType string       `json:"entityType"`
	Facts      []RecordFact `json:"facts"`
	Name       string       `json:"name"`
	Summary    string       `json:"summary"`
	UpdatedAt  time.Time    `json:"updatedAt"`
}

// RecordFact defines model for RecordFact.
type RecordFact struct {
	Key        string     `json:"key"`
	ObservedAt *time.Time `json:"observedAt,omitempty"`
	Value      string     `json:"value"`
}

// RecordsLookupRequest defines model for RecordsLookupRequest.
type RecordsLookupRequest struct {
	Cursor     *string `json:"cursor,omitempty"`
	EntityType *string `json:"entityType,omitempty"`
	Limit      *int    `json:"limit,omitempty"`
	Text       string  `json:"text"`
}

// RecordsLookupResponse defines model for RecordsLookupResponse.
type RecordsLookupResponse struct {
	Entities []RecordEntity `json:"entities"`
	PageInfo PageInfo       `json:"pageInfo"`
}

// ReplaceSectionRequest defines model for ReplaceSectionRequest.
type ReplaceSectionRequest struct {
	Content string `json:"content"`
	Heading string `json:"heading"`
}

// SearchHit defines model for SearchHit.
type SearchHit struct {
	ChunkId   string     `json:"chunkId"`
	Citations []Citation `json:"citations"`
	DocId     string     `json:"docId"`
	Rank      int        `json:"rank"`
	Score     float64    `json:"score"`
	Snippet   string     `json:"snippet"`
	Title     string     `json:"title"`
}

// SearchQuery defines model for SearchQuery.
type SearchQuery struct {
	Cursor *string `json:"cursor,omitempty"`
	Limit  *int    `json:"limit,omitempty"`
	Text   string  `json:"text"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Hits     []SearchHit `json:"hits"`
	PageInfo PageInfo    `json:"pageInfo"`
}

// ChunkId defines model for ChunkId.
type ChunkId = string

// DocId defines model for DocId.
type DocId = string

// EntityId defines model for EntityId.
type EntityId = string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = ErrorEnvelope

// CreateDocumentJSONRequestBody defines body for CreateDocument for application/json ContentType.
type CreateDocumentJSONRequestBody = CreateDocumentRequest

// AppendDocumentJSONRequestBody defines body for AppendDocument for application/json ContentType.
type AppendDocumentJSONRequestBody = AppendDocumentRequest

// ReplaceDocumentSectionJSONRequestBody defines body for ReplaceDocumentSection for application/json ContentType.
type ReplaceDocumentSectionJSONRequestBody = ReplaceSectionRequest

// GraphNeighborhoodJSONRequestBody defines body for GraphNeighborhood for application/json ContentType.
type GraphNeighborhoodJSONRequestBody = GraphNeighborhoodRequest

// RecordsLookupJSONRequestBody defines body for RecordsLookup for application/json ContentType.
type RecordsLookupJSONRequestBody = RecordsLookupRequest

// SearchQueryJSONRequestBody defines body for SearchQuery for application/json ContentType.
type SearchQueryJSONRequestBody = SearchQuery

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get backend capabilities
	// (GET /v1/capabilities)
	GetCapabilities(w http.ResponseWriter, r *http.Request)
	// Get an indexed chunk
	// (GET /v1/chunks/{chunkId})
	GetChunk(w http.ResponseWriter, r *http.Request, chunkId ChunkId)
	// Create a canonical markdown document
	// (POST /v1/documents)
	CreateDocument(w http.ResponseWriter, r *http.Request)
	// Get a canonical document
	// (GET /v1/documents/{docId})
	GetDocument(w http.ResponseWriter, r *http.Request, docId DocId)
	// Append markdown content to a canonical document
	// (POST /v1/documents/{docId}:append)
	AppendDocument(w http.ResponseWriter, r *http.Request, docId DocId)
	// Replace one heading-scoped section in a canonical document
	// (POST /v1/documents/{docId}:replace-section)
	ReplaceDocumentSection(w http.ResponseWriter, r *http.Request, docId DocId)
	// Get an evidence-linked graph neighborhood
	// (POST /v1/extensions/graph/neighborhood)
	GraphNeighborhood(w http.ResponseWriter, r *http.Request)
	// Get one promoted entity
	// (GET /v1/extensions/records/entities/{entityId})
	GetRecordEntity(w http.ResponseWriter, r *http.Request, entityId EntityId)
	// Lookup promoted records
	// (POST /v1/extensions/records/lookup)
	RecordsLookup(w http.ResponseWriter, r *http.Request)
	// Search indexed content
	// (POST /v1/search/query)
	SearchQuery(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCapabilities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCapabilities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChunk operation middleware
func (siw *ServerInterfaceWrapper) GetChunk(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "chunkId" -------------
	var chunkId ChunkId

	err = runtime.BindStyledParameterWithOptions("simple", "chunkId", r.PathValue("chunkId"), &chunkId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chunkId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChunk(w, r, chunkId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDocument operation middleware
func (siw *ServerInterfaceWrapper) CreateDocument(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDocument(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDocument operation middleware
func (siw *ServerInterfaceWrapper) GetDocument(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "docId" -------------
	var docId DocId

	err = runtime.BindStyledParameterWithOptions("simple", "docId", r.PathValue("docId"), &docId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "docId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDocument(w, r, docId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AppendDocument operation middleware
func (siw *ServerInterfaceWrapper) AppendDocument(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "docId" -------------
	var docId DocId

	err = runtime.BindStyledParameterWithOptions("simple", "docId", r.PathValue("docId"), &docId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "docId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AppendDocument(w, r, docId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaceDocumentSection operation middleware
func (siw *ServerInterfaceWrapper) ReplaceDocumentSection(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "docId" -------------
	var docId DocId

	err = runtime.BindStyledParameterWithOptions("simple", "docId", r.PathValue("docId"), &docId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "docId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaceDocumentSection(w, r, docId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GraphNeighborhood operation middleware
func (siw *ServerInterfaceWrapper) GraphNeighborhood(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GraphNeighborhood(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecordEntity operation middleware
func (siw *ServerInterfaceWrapper) GetRecordEntity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "entityId" -------------
	var entityId EntityId

	err = runtime.BindStyledParameterWithOptions("simple", "entityId", r.PathValue("entityId"), &entityId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entityId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecordEntity(w, r, entityId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecordsLookup operation middleware
func (siw *ServerInterfaceWrapper) RecordsLookup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordsLookup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchQuery operation middleware
func (siw *ServerInterfaceWrapper) SearchQuery(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchQuery(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/v1/capabilities", wrapper.GetCapabilities)
	m.HandleFunc("GET "+options.BaseURL+"/v1/chunks/{chunkId}", wrapper.GetChunk)
	m.HandleFunc("POST "+options.BaseURL+"/v1/documents", wrapper.CreateDocument)
	m.HandleFunc("GET "+options.BaseURL+"/v1/documents/{docId}", wrapper.GetDocument)
	m.HandleFunc("POST "+options.BaseURL+"/v1/documents/{docId}:append", wrapper.AppendDocument)
	m.HandleFunc("POST "+options.BaseURL+"/v1/documents/{docId}:replace-section", wrapper.ReplaceDocumentSection)
	m.HandleFunc("POST "+options.BaseURL+"/v1/extensions/graph/neighborhood", wrapper.GraphNeighborhood)
	m.HandleFunc("GET "+options.BaseURL+"/v1/extensions/records/entities/{entityId}", wrapper.GetRecordEntity)
	m.HandleFunc("POST "+options.BaseURL+"/v1/extensions/records/lookup", wrapper.RecordsLookup)
	m.HandleFunc("POST "+options.BaseURL+"/v1/search/query", wrapper.SearchQuery)

	return m
}

type ErrorResponseJSONResponse ErrorEnvelope

type GetCapabilitiesRequestObject struct {
}

type GetCapabilitiesResponseObject interface {
	VisitGetCapabilitiesResponse(w http.ResponseWriter) error
}

type GetCapabilities200JSONResponse Capabilities

func (response GetCapabilities200JSONResponse) VisitGetCapabilitiesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCapabilitiesdefaultJSONResponse struct {
	Body       ErrorEnvelope
	StatusCode int
}

func (response GetCapabilitiesdefaultJSONResponse) VisitGetCapabilitiesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetChunkRequestObject struct {
	ChunkId ChunkId `json:"chunkId"`
}

type GetChunkResponseObject interface {
	VisitGetChunkResponse(w http.ResponseWriter) error
}

type GetChunk200JSONResponse Chunk

func (response GetChunk200JSONResponse) VisitGetChunkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetChunkdefaultJSONResponse struct {
	Body       ErrorEnvelope
	StatusCode int
}

func (response GetChunkdefaultJSONResponse) VisitGetChunkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateDocumentRequestObject struct {
	Body *CreateDocumentJSONRequestBody
}

type CreateDocumentResponseObject interface {
	VisitCreateDocumentResponse(w http.ResponseWriter) error
}

type CreateDocument201JSONResponse Document

func (response CreateDocument201JSONResponse) VisitCreateDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDocumentdefaultJSONResponse struct {
	Body       ErrorEnvelope
	StatusCode int
}

func (response CreateDocumentdefaultJSONResponse) VisitCreateDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetDocumentRequestObject struct {
	DocId DocId `json:"docId"`
}

type GetDocumentResponseObject interface {
	VisitGetDocumentResponse(w http.ResponseWriter) error
}

type GetDocument200JSONResponse Document

func (response GetDocument200JSONResponse) VisitGetDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDocumentdefaultJSONResponse struct {
	Body       ErrorEnvelope
	StatusCode int
}

func (response GetDocumentdefaultJSONResponse) VisitGetDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type AppendDocumentRequestObject struct {
	DocId DocId `json:"docId"`
	Body  *AppendDocumentJSONRequestBody
}

type AppendDocumentResponseObject interface {
	VisitAppendDocumentResponse(w http.ResponseWriter) error
}

type AppendDocument200JSONResponse Document

func (response AppendDocument200JSONResponse) VisitAppendDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AppendDocumentdefaultJSONResponse struct {
	Body       ErrorEnvelope
	StatusCode int
}

func (response AppendDocumentdefaultJSONResponse) VisitAppendDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ReplaceDocumentSectionRequestObject struct {
	DocId DocId `json:"docId"`
	Body  *ReplaceDocumentSectionJSONRequestBody
}

type ReplaceDocumentSectionResponseObject interface {
	VisitReplaceDocumentSectionResponse(w http.ResponseWriter) error
}

type ReplaceDocumentSection200JSONResponse Document

func (response ReplaceDocumentSection200JSONResponse) VisitReplaceDocumentSectionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ReplaceDocumentSectiondefaultJSONResponse struct {
	Body       ErrorEnvelope
	StatusCode int
}

func (response ReplaceDocumentSectiondefaultJSONResponse) VisitReplaceDocumentSectionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GraphNeighborhoodRequestObject struct {
	Body *GraphNeighborhoodJSONRequestBody
}

type GraphNeighborhoodResponseObject interface {
	VisitGraphNeighborhoodResponse(w http.ResponseWriter) error
}

type GraphNeighborhood200JSONResponse GraphNeighborhoodResponse

func (response GraphNeighborhood200JSONResponse) VisitGraphNeighborhoodResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GraphNeighborhooddefaultJSONResponse struct {
	Body       ErrorEnvelope
	StatusCode int
}

func (response GraphNeighborhooddefaultJSONResponse) VisitGraphNeighborhoodResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetRecordEntityRequestObject struct {
	EntityId EntityId `json:"entityId"`
}

type GetRecordEntityResponseObject interface {
	VisitGetRecordEntityResponse(w http.ResponseWriter) error
}

type GetRecordEntity200JSONResponse RecordEntity

func (response GetRecordEntity200JSONResponse) VisitGetRecordEntityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRecordEntitydefaultJSONResponse struct {
	Body       ErrorEnvelope
	StatusCode int
}

func (response GetRecordEntitydefaultJSONResponse) VisitGetRecordEntityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type RecordsLookupRequestObject struct {
	Body *RecordsLookupJSONRequestBody
}

type RecordsLookupResponseObject interface {
	VisitRecordsLookupResponse(w http.ResponseWriter) error
}

type RecordsLookup200JSONResponse RecordsLookupResponse

func (response RecordsLookup200JSONResponse) VisitRecordsLookupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RecordsLookupdefaultJSONResponse struct {
	Body       ErrorEnvelope
	StatusCode int
}

func (response RecordsLookupdefaultJSONResponse) VisitRecordsLookupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type SearchQueryRequestObject struct {
	Body *SearchQueryJSONRequestBody
}

type SearchQueryResponseObject interface {
	VisitSearchQueryResponse(w http.ResponseWriter) error
}

type SearchQuery200JSONResponse SearchResponse

func (response SearchQuery200JSONResponse) VisitSearchQueryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchQuerydefaultJSONResponse struct {
	Body       ErrorEnvelope
	StatusCode int
}

func (response SearchQuerydefaultJSONResponse) VisitSearchQueryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get backend capabilities
	// (GET /v1/capabilities)
	GetCapabilities(ctx context.Context, request GetCapabilitiesRequestObject) (GetCapabilitiesResponseObject, error)
	// Get an indexed chunk
	// (GET /v1/chunks/{chunkId})
	GetChunk(ctx context.Context, request GetChunkRequestObject) (GetChunkResponseObject, error)
	// Create a canonical markdown document
	// (POST /v1/documents)
	CreateDocument(ctx context.Context, request CreateDocumentRequestObject) (CreateDocumentResponseObject, error)
	// Get a canonical document
	// (GET /v1/documents/{docId})
	GetDocument(ctx context.Context, request GetDocumentRequestObject) (GetDocumentResponseObject, error)
	// Append markdown content to a canonical document
	// (POST /v1/documents/{docId}:append)
	AppendDocument(ctx context.Context, request AppendDocumentRequestObject) (AppendDocumentResponseObject, error)
	// Replace one heading-scoped section in a canonical document
	// (POST /v1/documents/{docId}:replace-section)
	ReplaceDocumentSection(ctx context.Context, request ReplaceDocumentSectionRequestObject) (ReplaceDocumentSectionResponseObject, error)
	// Get an evidence-linked graph neighborhood
	// (POST /v1/extensions/graph/neighborhood)
	GraphNeighborhood(ctx context.Context, request GraphNeighborhoodRequestObject) (GraphNeighborhoodResponseObject, error)
	// Get one promoted entity
	// (GET /v1/extensions/records/entities/{entityId})
	GetRecordEntity(ctx context.Context, request GetRecordEntityRequestObject) (GetRecordEntityResponseObject, error)
	// Lookup promoted records
	// (POST /v1/extensions/records/lookup)
	RecordsLookup(ctx context.Context, request RecordsLookupRequestObject) (RecordsLookupResponseObject, error)
	// Search indexed content
	// (POST /v1/search/query)
	SearchQuery(ctx context.Context, request SearchQueryRequestObject) (SearchQueryResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetCapabilities operation middleware
func (sh *strictHandler) GetCapabilities(w http.ResponseWriter, r *http.Request) {
	var request GetCapabilitiesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCapabilities(ctx, request.(GetCapabilitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCapabilities")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCapabilitiesResponseObject); ok {
		if err := validResponse.VisitGetCapabilitiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetChunk operation middleware
func (sh *strictHandler) GetChunk(w http.ResponseWriter, r *http.Request, chunkId ChunkId) {
	var request GetChunkRequestObject

	request.ChunkId = chunkId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetChunk(ctx, request.(GetChunkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetChunk")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetChunkResponseObject); ok {
		if err := validResponse.VisitGetChunkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDocument operation middleware
func (sh *strictHandler) CreateDocument(w http.ResponseWriter, r *http.Request) {
	var request CreateDocumentRequestObject

	var body CreateDocumentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDocument(ctx, request.(CreateDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDocumentResponseObject); ok {
		if err := validResponse.VisitCreateDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDocument operation middleware
func (sh *strictHandler) GetDocument(w http.ResponseWriter, r *http.Request, docId DocId) {
	var request GetDocumentRequestObject

	request.DocId = docId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDocument(ctx, request.(GetDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDocumentResponseObject); ok {
		if err := validResponse.VisitGetDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AppendDocument operation middleware
func (sh *strictHandler) AppendDocument(w http.ResponseWriter, r *http.Request, docId DocId) {
	var request AppendDocumentRequestObject

	request.DocId = docId

	var body AppendDocumentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AppendDocument(ctx, request.(AppendDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AppendDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AppendDocumentResponseObject); ok {
		if err := validResponse.VisitAppendDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReplaceDocumentSection operation middleware
func (sh *strictHandler) ReplaceDocumentSection(w http.ResponseWriter, r *http.Request, docId DocId) {
	var request ReplaceDocumentSectionRequestObject

	request.DocId = docId

	var body ReplaceDocumentSectionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReplaceDocumentSection(ctx, request.(ReplaceDocumentSectionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReplaceDocumentSection")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReplaceDocumentSectionResponseObject); ok {
		if err := validResponse.VisitReplaceDocumentSectionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GraphNeighborhood operation middleware
func (sh *strictHandler) GraphNeighborhood(w http.ResponseWriter, r *http.Request) {
	var request GraphNeighborhoodRequestObject

	var body GraphNeighborhoodJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GraphNeighborhood(ctx, request.(GraphNeighborhoodRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GraphNeighborhood")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GraphNeighborhoodResponseObject); ok {
		if err := validResponse.VisitGraphNeighborhoodResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRecordEntity operation middleware
func (sh *strictHandler) GetRecordEntity(w http.ResponseWriter, r *http.Request, entityId EntityId) {
	var request GetRecordEntityRequestObject

	request.EntityId = entityId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRecordEntity(ctx, request.(GetRecordEntityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRecordEntity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRecordEntityResponseObject); ok {
		if err := validResponse.VisitGetRecordEntityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RecordsLookup operation middleware
func (sh *strictHandler) RecordsLookup(w http.ResponseWriter, r *http.Request) {
	var request RecordsLookupRequestObject

	var body RecordsLookupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RecordsLookup(ctx, request.(RecordsLookupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RecordsLookup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RecordsLookupResponseObject); ok {
		if err := validResponse.VisitRecordsLookupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchQuery operation middleware
func (sh *strictHandler) SearchQuery(w http.ResponseWriter, r *http.Request) {
	var request SearchQueryRequestObject

	var body SearchQueryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchQuery(ctx, request.(SearchQueryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchQuery")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchQueryResponseObject); ok {
		if err := validResponse.VisitSearchQueryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
