// Package fts provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package fts

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for CapabilitiesAuthMode.
const (
	None CapabilitiesAuthMode = "none"
)

// Valid indicates whether the value is a known member of the CapabilitiesAuthMode enum.
func (e CapabilitiesAuthMode) Valid() bool {
	switch e {
	case None:
		return true
	default:
		return false
	}
}

// Defines values for CapabilitiesBackend.
const (
	CapabilitiesBackendFts     CapabilitiesBackend = "fts"
	CapabilitiesBackendGraph   CapabilitiesBackend = "graph"
	CapabilitiesBackendHybrid  CapabilitiesBackend = "hybrid"
	CapabilitiesBackendRecords CapabilitiesBackend = "records"
)

// Valid indicates whether the value is a known member of the CapabilitiesBackend enum.
func (e CapabilitiesBackend) Valid() bool {
	switch e {
	case CapabilitiesBackendFts:
		return true
	case CapabilitiesBackendGraph:
		return true
	case CapabilitiesBackendHybrid:
		return true
	case CapabilitiesBackendRecords:
		return true
	default:
		return false
	}
}

// Defines values for CapabilitiesExtensions.
const (
	CapabilitiesExtensionsGraph   CapabilitiesExtensions = "graph"
	CapabilitiesExtensionsRecords CapabilitiesExtensions = "records"
)

// Valid indicates whether the value is a known member of the CapabilitiesExtensions enum.
func (e CapabilitiesExtensions) Valid() bool {
	switch e {
	case CapabilitiesExtensionsGraph:
		return true
	case CapabilitiesExtensionsRecords:
		return true
	default:
		return false
	}
}

// Defines values for CapabilitiesSearchModes.
const (
	Hybrid  CapabilitiesSearchModes = "hybrid"
	Lexical CapabilitiesSearchModes = "lexical"
	Vector  CapabilitiesSearchModes = "vector"
)

// Valid indicates whether the value is a known member of the CapabilitiesSearchModes enum.
func (e CapabilitiesSearchModes) Valid() bool {
	switch e {
	case Hybrid:
		return true
	case Lexical:
		return true
	case Vector:
		return true
	default:
		return false
	}
}

// Defines values for GraphEdgeKind.
const (
	Cites    GraphEdgeKind = "cites"
	LinksTo  GraphEdgeKind = "links_to"
	Mentions GraphEdgeKind = "mentions"
)

// Valid indicates whether the value is a known member of the GraphEdgeKind enum.
func (e GraphEdgeKind) Valid() bool {
	switch e {
	case Cites:
		return true
	case LinksTo:
		return true
	case Mentions:
		return true
	default:
		return false
	}
}

// Defines values for GraphNodeType.
const (
	GraphNodeTypeChunk    GraphNodeType = "chunk"
	GraphNodeTypeDocument GraphNodeType = "document"
	GraphNodeTypeEntity   GraphNodeType = "entity"
	GraphNodeTypeHeading  GraphNodeType = "heading"
)

// Valid indicates whether the value is a known member of the GraphNodeType enum.
func (e GraphNodeType) Valid() bool {
	switch e {
	case GraphNodeTypeChunk:
		return true
	case GraphNodeTypeDocument:
		return true
	case GraphNodeTypeEntity:
		return true
	case GraphNodeTypeHeading:
		return true
	default:
		return false
	}
}

// AppendDocumentRequest defines model for AppendDocumentRequest.
type AppendDocumentRequest struct {
	Content string `json:"content"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	AuthMode    CapabilitiesAuthMode      `json:"authMode"`
	Backend     CapabilitiesBackend       `json:"backend"`
	Extensions  []CapabilitiesExtensions  `json:"extensions"`
	SearchModes []CapabilitiesSearchModes `json:"searchModes"`
}

// CapabilitiesAuthMode defines model for Capabilities.AuthMode.
type CapabilitiesAuthMode string

// CapabilitiesBackend defines model for Capabilities.Backend.
type CapabilitiesBackend string

// CapabilitiesExtensions defines model for Capabilities.Extensions.
type CapabilitiesExtensions string

// CapabilitiesSearchModes defines model for Capabilities.SearchModes.
type CapabilitiesSearchModes string

// Chunk defines model for Chunk.
type Chunk struct {
	ChunkId   string `json:"chunkId"`
	Content   string `json:"content"`
	DocId     string `json:"docId"`
	Heading   string `json:"heading"`
	LineEnd   int    `json:"lineEnd"`
	LineStart int    `json:"lineStart"`
	Path      string `json:"path"`
}

// Citation defines model for Citation.
type Citation struct {
	ChunkId   string  `json:"chunkId"`
	DocId     string  `json:"docId"`
	Heading   *string `json:"heading,omitempty"`
	LineEnd   int     `json:"lineEnd"`
	LineStart int     `json:"lineStart"`
	Path      string  `json:"path"`
}

// CreateDocumentRequest defines model for CreateDocumentRequest.
type CreateDocumentRequest struct {
	Body  string `json:"body"`
	Path  string `json:"path"`
	Title string `json:"title"`
}

// Document defines model for Document.
type Document struct {
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"createdAt"`
	DocId     string    `json:"docId"`
	Headings  []string  `json:"headings"`
	Path      string    `json:"path"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Code      string                  `json:"code"`
	Details   *map[string]interface{} `json:"details,omitempty"`
	Message   string                  `json:"message"`
	RequestId string                  `json:"requestId"`
	Retryable bool                    `json:"retryable"`
}

// GraphEdge defines model for GraphEdge.
type GraphEdge struct {
	Citations  []Citation    `json:"citations"`
	EdgeId     string        `json:"edgeId"`
	FromNodeId string        `json:"fromNodeId"`
	Kind       GraphEdgeKind `json:"kind"`
	ToNodeId   string        `json:"toNodeId"`
}

// GraphEdgeKind defines model for GraphEdge.Kind.
type GraphEdgeKind string

// GraphNeighborhoodRequest defines model for GraphNeighborhoodRequest.
type GraphNeighborhoodRequest struct {
	ChunkId *string `json:"chunkId,omitempty"`
	DocId   *string `json:"docId,omitempty"`
	Limit   *int    `json:"limit,omitempty"`
	NodeId  *string `json:"nodeId,omitempty"`
}

// GraphNeighborhoodResponse defines model for GraphNeighborhoodResponse.
type GraphNeighborhoodResponse struct {
	Edges []GraphEdge `json:"edges"`
	Nodes []GraphNode `json:"nodes"`
}

// GraphNode defines model for GraphNode.
type GraphNode struct {
	Citations []Citation    `json:"citations"`
	Label     string        `json:"label"`
	NodeId    string        `json:"nodeId"`
	Type      GraphNodeType `json:"type"`
}

// GraphNodeType defines model for GraphNode.Type.
type GraphNodeType string

// PageInfo defines model for PageInfo.
type PageInfo struct {
	HasMore    bool    `json:"hasMore"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

// RecordEntity defines model for RecordEntity.
type RecordEntity struct {
	Citations  []Citation   `json:"citations"`
	EntityId   string       `json:"entityId"`
	EntityType string       `json:"entityType"`
	Facts      []RecordFact `json:"facts"`
	Name       string       `json:"name"`
	Summary    string       `json:"summary"`
	UpdatedAt  time.Time    `json:"updatedAt"`
}

// RecordFact defines model for RecordFact.
type RecordFact struct {
	Key        string     `json:"key"`
	ObservedAt *time.Time `json:"observedAt,omitempty"`
	Value      string     `json:"value"`
}

// RecordsLookupRequest defines model for RecordsLookupRequest.
type RecordsLookupRequest struct {
	Cursor     *string `json:"cursor,omitempty"`
	EntityType *string `json:"entityType,omitempty"`
	Limit      *int    `json:"limit,omitempty"`
	Text       string  `json:"text"`
}

// RecordsLookupResponse defines model for RecordsLookupResponse.
type RecordsLookupResponse struct {
	Entities []RecordEntity `json:"entities"`
	PageInfo PageInfo       `json:"pageInfo"`
}

// ReplaceSectionRequest defines model for ReplaceSectionRequest.
type ReplaceSectionRequest struct {
	Content string `json:"content"`
	Heading string `json:"heading"`
}

// SearchHit defines model for SearchHit.
type SearchHit struct {
	ChunkId   string     `json:"chunkId"`
	Citations []Citation `json:"citations"`
	DocId     string     `json:"docId"`
	Rank      int        `json:"rank"`
	Score     float64    `json:"score"`
	Snippet   string     `json:"snippet"`
	Title     string     `json:"title"`
}

// SearchQuery defines model for SearchQuery.
type SearchQuery struct {
	Cursor *string `json:"cursor,omitempty"`
	Limit  *int    `json:"limit,omitempty"`
	Text   string  `json:"text"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Hits     []SearchHit `json:"hits"`
	PageInfo PageInfo    `json:"pageInfo"`
}

// ChunkId defines model for ChunkId.
type ChunkId = string

// DocId defines model for DocId.
type DocId = string

// EntityId defines model for EntityId.
type EntityId = string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = ErrorEnvelope

// CreateDocumentJSONRequestBody defines body for CreateDocument for application/json ContentType.
type CreateDocumentJSONRequestBody = CreateDocumentRequest

// AppendDocumentJSONRequestBody defines body for AppendDocument for application/json ContentType.
type AppendDocumentJSONRequestBody = AppendDocumentRequest

// ReplaceDocumentSectionJSONRequestBody defines body for ReplaceDocumentSection for application/json ContentType.
type ReplaceDocumentSectionJSONRequestBody = ReplaceSectionRequest

// SearchQueryJSONRequestBody defines body for SearchQuery for application/json ContentType.
type SearchQueryJSONRequestBody = SearchQuery

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetCapabilities request
	GetCapabilities(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetChunk request
	GetChunk(ctx context.Context, chunkId ChunkId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateDocumentWithBody request with any body
	CreateDocumentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateDocument(ctx context.Context, body CreateDocumentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDocument request
	GetDocument(ctx context.Context, docId DocId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AppendDocumentWithBody request with any body
	AppendDocumentWithBody(ctx context.Context, docId DocId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AppendDocument(ctx context.Context, docId DocId, body AppendDocumentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReplaceDocumentSectionWithBody request with any body
	ReplaceDocumentSectionWithBody(ctx context.Context, docId DocId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ReplaceDocumentSection(ctx context.Context, docId DocId, body ReplaceDocumentSectionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchQueryWithBody request with any body
	SearchQueryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SearchQuery(ctx context.Context, body SearchQueryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetCapabilities(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCapabilitiesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetChunk(ctx context.Context, chunkId ChunkId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetChunkRequest(c.Server, chunkId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDocumentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDocumentRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDocument(ctx context.Context, body CreateDocumentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDocumentRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDocument(ctx context.Context, docId DocId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDocumentRequest(c.Server, docId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AppendDocumentWithBody(ctx context.Context, docId DocId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAppendDocumentRequestWithBody(c.Server, docId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AppendDocument(ctx context.Context, docId DocId, body AppendDocumentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAppendDocumentRequest(c.Server, docId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReplaceDocumentSectionWithBody(ctx context.Context, docId DocId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceDocumentSectionRequestWithBody(c.Server, docId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReplaceDocumentSection(ctx context.Context, docId DocId, body ReplaceDocumentSectionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceDocumentSectionRequest(c.Server, docId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchQueryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchQueryRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchQuery(ctx context.Context, body SearchQueryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchQueryRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCapabilitiesRequest generates requests for GetCapabilities
func NewGetCapabilitiesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/capabilities")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetChunkRequest generates requests for GetChunk
func NewGetChunkRequest(server string, chunkId ChunkId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "chunkId", chunkId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/chunks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateDocumentRequest calls the generic CreateDocument builder with application/json body
func NewCreateDocumentRequest(server string, body CreateDocumentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateDocumentRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateDocumentRequestWithBody generates requests for CreateDocument with any type of body
func NewCreateDocumentRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/documents")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetDocumentRequest generates requests for GetDocument
func NewGetDocumentRequest(server string, docId DocId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "docId", docId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/documents/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAppendDocumentRequest calls the generic AppendDocument builder with application/json body
func NewAppendDocumentRequest(server string, docId DocId, body AppendDocumentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAppendDocumentRequestWithBody(server, docId, "application/json", bodyReader)
}

// NewAppendDocumentRequestWithBody generates requests for AppendDocument with any type of body
func NewAppendDocumentRequestWithBody(server string, docId DocId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "docId", docId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/documents/%s:append", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReplaceDocumentSectionRequest calls the generic ReplaceDocumentSection builder with application/json body
func NewReplaceDocumentSectionRequest(server string, docId DocId, body ReplaceDocumentSectionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReplaceDocumentSectionRequestWithBody(server, docId, "application/json", bodyReader)
}

// NewReplaceDocumentSectionRequestWithBody generates requests for ReplaceDocumentSection with any type of body
func NewReplaceDocumentSectionRequestWithBody(server string, docId DocId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "docId", docId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/documents/%s:replace-section", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSearchQueryRequest calls the generic SearchQuery builder with application/json body
func NewSearchQueryRequest(server string, body SearchQueryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSearchQueryRequestWithBody(server, "application/json", bodyReader)
}

// NewSearchQueryRequestWithBody generates requests for SearchQuery with any type of body
func NewSearchQueryRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/search/query")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetCapabilitiesWithResponse request
	GetCapabilitiesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCapabilitiesResp, error)

	// GetChunkWithResponse request
	GetChunkWithResponse(ctx context.Context, chunkId ChunkId, reqEditors ...RequestEditorFn) (*GetChunkResp, error)

	// CreateDocumentWithBodyWithResponse request with any body
	CreateDocumentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDocumentResp, error)

	CreateDocumentWithResponse(ctx context.Context, body CreateDocumentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDocumentResp, error)

	// GetDocumentWithResponse request
	GetDocumentWithResponse(ctx context.Context, docId DocId, reqEditors ...RequestEditorFn) (*GetDocumentResp, error)

	// AppendDocumentWithBodyWithResponse request with any body
	AppendDocumentWithBodyWithResponse(ctx context.Context, docId DocId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AppendDocumentResp, error)

	AppendDocumentWithResponse(ctx context.Context, docId DocId, body AppendDocumentJSONRequestBody, reqEditors ...RequestEditorFn) (*AppendDocumentResp, error)

	// ReplaceDocumentSectionWithBodyWithResponse request with any body
	ReplaceDocumentSectionWithBodyWithResponse(ctx context.Context, docId DocId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReplaceDocumentSectionResp, error)

	ReplaceDocumentSectionWithResponse(ctx context.Context, docId DocId, body ReplaceDocumentSectionJSONRequestBody, reqEditors ...RequestEditorFn) (*ReplaceDocumentSectionResp, error)

	// SearchQueryWithBodyWithResponse request with any body
	SearchQueryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SearchQueryResp, error)

	SearchQueryWithResponse(ctx context.Context, body SearchQueryJSONRequestBody, reqEditors ...RequestEditorFn) (*SearchQueryResp, error)
}

type GetCapabilitiesResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Capabilities
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetCapabilitiesResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCapabilitiesResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetChunkResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Chunk
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetChunkResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetChunkResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateDocumentResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Document
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateDocumentResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateDocumentResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDocumentResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Document
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetDocumentResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDocumentResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AppendDocumentResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Document
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r AppendDocumentResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AppendDocumentResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ReplaceDocumentSectionResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Document
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ReplaceDocumentSectionResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReplaceDocumentSectionResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SearchQueryResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SearchResponse
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r SearchQueryResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchQueryResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetCapabilitiesWithResponse request returning *GetCapabilitiesResp
func (c *ClientWithResponses) GetCapabilitiesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCapabilitiesResp, error) {
	rsp, err := c.GetCapabilities(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCapabilitiesResp(rsp)
}

// GetChunkWithResponse request returning *GetChunkResp
func (c *ClientWithResponses) GetChunkWithResponse(ctx context.Context, chunkId ChunkId, reqEditors ...RequestEditorFn) (*GetChunkResp, error) {
	rsp, err := c.GetChunk(ctx, chunkId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetChunkResp(rsp)
}

// CreateDocumentWithBodyWithResponse request with arbitrary body returning *CreateDocumentResp
func (c *ClientWithResponses) CreateDocumentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDocumentResp, error) {
	rsp, err := c.CreateDocumentWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDocumentResp(rsp)
}

func (c *ClientWithResponses) CreateDocumentWithResponse(ctx context.Context, body CreateDocumentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDocumentResp, error) {
	rsp, err := c.CreateDocument(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDocumentResp(rsp)
}

// GetDocumentWithResponse request returning *GetDocumentResp
func (c *ClientWithResponses) GetDocumentWithResponse(ctx context.Context, docId DocId, reqEditors ...RequestEditorFn) (*GetDocumentResp, error) {
	rsp, err := c.GetDocument(ctx, docId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDocumentResp(rsp)
}

// AppendDocumentWithBodyWithResponse request with arbitrary body returning *AppendDocumentResp
func (c *ClientWithResponses) AppendDocumentWithBodyWithResponse(ctx context.Context, docId DocId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AppendDocumentResp, error) {
	rsp, err := c.AppendDocumentWithBody(ctx, docId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAppendDocumentResp(rsp)
}

func (c *ClientWithResponses) AppendDocumentWithResponse(ctx context.Context, docId DocId, body AppendDocumentJSONRequestBody, reqEditors ...RequestEditorFn) (*AppendDocumentResp, error) {
	rsp, err := c.AppendDocument(ctx, docId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAppendDocumentResp(rsp)
}

// ReplaceDocumentSectionWithBodyWithResponse request with arbitrary body returning *ReplaceDocumentSectionResp
func (c *ClientWithResponses) ReplaceDocumentSectionWithBodyWithResponse(ctx context.Context, docId DocId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReplaceDocumentSectionResp, error) {
	rsp, err := c.ReplaceDocumentSectionWithBody(ctx, docId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplaceDocumentSectionResp(rsp)
}

func (c *ClientWithResponses) ReplaceDocumentSectionWithResponse(ctx context.Context, docId DocId, body ReplaceDocumentSectionJSONRequestBody, reqEditors ...RequestEditorFn) (*ReplaceDocumentSectionResp, error) {
	rsp, err := c.ReplaceDocumentSection(ctx, docId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplaceDocumentSectionResp(rsp)
}

// SearchQueryWithBodyWithResponse request with arbitrary body returning *SearchQueryResp
func (c *ClientWithResponses) SearchQueryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SearchQueryResp, error) {
	rsp, err := c.SearchQueryWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchQueryResp(rsp)
}

func (c *ClientWithResponses) SearchQueryWithResponse(ctx context.Context, body SearchQueryJSONRequestBody, reqEditors ...RequestEditorFn) (*SearchQueryResp, error) {
	rsp, err := c.SearchQuery(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchQueryResp(rsp)
}

// ParseGetCapabilitiesResp parses an HTTP response from a GetCapabilitiesWithResponse call
func ParseGetCapabilitiesResp(rsp *http.Response) (*GetCapabilitiesResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCapabilitiesResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Capabilities
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetChunkResp parses an HTTP response from a GetChunkWithResponse call
func ParseGetChunkResp(rsp *http.Response) (*GetChunkResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetChunkResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Chunk
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateDocumentResp parses an HTTP response from a CreateDocumentWithResponse call
func ParseCreateDocumentResp(rsp *http.Response) (*CreateDocumentResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateDocumentResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Document
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetDocumentResp parses an HTTP response from a GetDocumentWithResponse call
func ParseGetDocumentResp(rsp *http.Response) (*GetDocumentResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDocumentResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Document
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseAppendDocumentResp parses an HTTP response from a AppendDocumentWithResponse call
func ParseAppendDocumentResp(rsp *http.Response) (*AppendDocumentResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AppendDocumentResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Document
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseReplaceDocumentSectionResp parses an HTTP response from a ReplaceDocumentSectionWithResponse call
func ParseReplaceDocumentSectionResp(rsp *http.Response) (*ReplaceDocumentSectionResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReplaceDocumentSectionResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Document
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseSearchQueryResp parses an HTTP response from a SearchQueryWithResponse call
func ParseSearchQueryResp(rsp *http.Response) (*SearchQueryResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchQueryResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SearchResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
